USE carsurfing;

CREATE TABLE user
(
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50) NOT NULL,
  MIDDLE_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(256) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL UNIQUE,
  PHONE VARCHAR(10) NOT NULL UNIQUE,
  VERIFIED VARCHAR(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ride
(
  ID INT  NOT NULL AUTO_INCREMENT,
  DRIVER_ID INT  NOT NULL, 
  FROM_LOCATION VARCHAR(20)  NOT NULL,
  TO_LOCATION VARCHAR(20)  NOT NULL,
  DATE_OF_DEPARTURE DATE  NOT NULL,
  ESTIMATED_DEPARTURE_TIME TIME,
  STOP_1 VARCHAR(20),
  STOP_2 VARCHAR(20),
  STOP_3 VARCHAR(20),
  SPACES_LEFT INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (DRIVER_ID) REFERENCES user(ID)
);

CREATE TABLE bookings
(
  ID INT NOT NULL AUTO_INCREMENT,
  RIDE_ID INT  NOT NULL,
  PASSENGER_ID INT  NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (PASSENGER_ID) REFERENCES user(ID),
  FOREIGN KEY (RIDE_ID) REFERENCES ride(ID)
);

CREATE TABLE review (
  ID int NOT NULL AUTO_INCREMENT,
  REVIEWER_NAME varchar(256) NOT NULL,
  REVIEWED_ID int NOT NULL,
  COMMENT varchar(3000) DEFAULT NULL,
  RATING int NOT NULL,
  PRIMARY KEY (ID),
  KEY REVIEWER_ID (REVIEWER_NAME),
  KEY REVIEWED_ID (REVIEWED_ID),
  CONSTRAINT reviews_ibfk_2 FOREIGN KEY (REVIEWED_ID) REFERENCES user (ID) ON DELETE CASCADE
);


insert into user values(0,'Sorcha','Jenny','Murtagh','','jennymurtagh@yahoo.com','0874123456','Yes');
insert into user values(0,'Robert','','Smith','funny person','robertS45@yahoo.com','089977546','Yes');
insert into user values(0,'John','Sean','Kennedy','pet owner','seankennedy777@gmail.com','087689800','Yes');
insert into user values(0,'Mary','Diana','Fernandez','','fernandezm@gmail.com','0874343563','Yes');
